<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace common\models\base;

use Yii;

/**
 * This is the base-model class for table "p2m_group".
 *
 * @property integer $group_id
 * @property integer $category_id
 * @property string $name
 * @property string $title
 * @property integer $hide
 *
 * @property \common\models\Category $category
 * @property \common\models\Subgroup[] $subgroups
 * @property string $aliasModel
 */
abstract class Group extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'p2m_group';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['category_id', 'name', 'title'], 'required'],
            [['category_id', 'hide'], 'integer'],
            [['name', 'title'], 'string', 'max' => 32],
            [['name'], 'unique'],
            [['category_id'], 'exist', 'skipOnError' => true, 'targetClass' => \common\models\Category::className(), 'targetAttribute' => ['category_id' => 'category_id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'group_id' => 'Group ID',
            'category_id' => 'Category ID',
            'name' => 'Name',
            'title' => 'Title',
            'hide' => 'Hide',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCategory()
    {
        return $this->hasOne(\common\models\Category::className(), ['category_id' => 'category_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSubgroups()
    {
        return $this->hasMany(\common\models\Subgroup::className(), ['group_id' => 'group_id']);
    }



    /**
     * @inheritdoc
     * @return \common\models\GroupQuery the active query used by this AR class.
     */
    public static function find()
    {
        return new \common\models\GroupQuery(get_called_class());
    }


}
