<?php
$steppeData = [
	'video' => [
		['meta' => 'Abay Begey and Berik - Aspanga (Official video)', 'artist' => 'Abay Begey & Berik', 'artistQ' => 'Абай Бегей и Берик', 'title' => 'Aspanga', 'titleQ' => 'Аспанга', 'tag' => '2aMpbJuFDNI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2yNnS8Oj0GU'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '3-ItQs8IH2I'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '36JkWMz111Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '3SGXMZNAe9E'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '4vO729YWnVE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '54_TLvCzbmE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '5WxLJU8qR8A'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '5Zs-KBhvbB0'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '6PWSMtAwOB4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '7FjwDmzsklE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '8m053l20G8k'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '8QVPkSS_4Yc'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '8W_4h5hzoew'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '8W_BqnFXqxA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '9efIWFhD8a4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '9ZfFx5-jLCo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'A4jmQSVJsFI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'aa1w6pREua8'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ADwzxqyfCKA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'aeGVqDPZvmg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'B0NxgIwaDwk'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'bhWrtHdm7bA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'bJFMeF9m8tA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'bRStXxyLLQs'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'BYOj1yNa2Gw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'c9UeoCXiyb4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'CcPebbSoDnw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'DbQnIA61K5o'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'DHIziY5pA6s'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'dmANlpEhIBI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'dz-ydKICX-4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'DZt67UAE5pE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'EjiSUynPqOM'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ESBtBXOYznA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'f1GZREaDe1Y'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'F3a4cYc8o3c'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'f7jy66ng_bg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'FlfqRd1Wdqo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'fLqXLryH8xk'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'fsT3324VwY4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'fZaEEGw7eis'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'gPeKWNAWD9Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'gppQ-mMx1Q0'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'GR4RiAB-abQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'h61lMPzrG9w'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'hP20vJNwlOk'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'jsEDj3XOO3k'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'K6tSh5tN8ps'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'KbhQJomUeKA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'kR-miTRF9P4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'kZflInXzJ2w'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'L0tbiIZK2eQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'L2V47IqlXFY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'LfDOs8Z54B8'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'lFebp7XEjpY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'lWXy1Y1J7qI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'm1Ufa4aY450'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'mxIg7-8CyjA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'mYUt-76Wn4E'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'NkL4F6P2IvU'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'nkO6a-cQ4xA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'nwA1zQllN1g'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'O1ctSfIMnMc'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'o2nNXAu4GZU'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'oevYQoTujmo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ojfn8ivjNoo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Owgjjbz4_o4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'p5W1JmEJMHk'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'pCsfd644MBw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'PD-0j8KXWhQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'PLJ5jBSgO1g'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'pTWzFYhwWW0'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Pu2g1_P60Bs'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Q3951Rw0lBA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'q4_JMLukEIk'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'qd9GfRU0z3Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'qhdHis7tbVI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'QtMp9AAF1_8'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'R-MRP5AAqOI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Ra4v19Rp6cQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'rLh_DnkbysA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'RnVjEZfiyCg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Rx9vZeTGckY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ryWH0wLDr8w'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'sibgrBo_WAI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'SjyqejDb99c'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'SL97ViF_9DU'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'SmtuxfWXtBA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'T_k0HDa_5Ks'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 't44wrMO1KCo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'T9jL_EwPLjs'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'tefIH9ZzAGo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'tfKZ4RX--zc'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'tohU2g0pDeQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'tPnLhidHBcY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'TTOtM7oyyjE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'TW6xED_omZo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ty25u8Kdh20'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'U9YKzd9y5gk'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'uA1O6su3H6E'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'UfFo68QSYCY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'UnwcyaGYngY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'UTV9QG8O8qE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'uWxvrnrmfX8'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'UZdfhYKGfpw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'VcmdcJs0HLY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'VcZQOTIPxOo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'vmtvI3YMfao'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'VtjYRVx-XUI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'WE9ZjjVhntA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'wGfGs2DKFnA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'x_Ws7rNzcGI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'XaQFfqC3lnU'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Xse60t5tTUQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'XWIh_AJRsDQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Y0_ey4lz-OE'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Y9yHWfbU6KY'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'yb6XYuBWlf0'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'YlRkVAmHrSo'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'yOzUhadNRIU'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'YzQknv9Z9y8'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Z-XRjETfV9Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'zfw3R6D_xxQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Ziv7tGLxgS4'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ZLPYD6WlRdc'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ZOgS2u4anaI'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Zu4dcJe6vB8'],
		['meta' => 'Alkissa, Makhambet (poem) - N.Tlendiev 1998', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '_l7KjBazOzo'],
		['meta' => 'Tamara Asar - Renjimeshi', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '128tkw1VfYI'],
		['meta' => 'Jurabek Juraev in Moscow!', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '1lnk7HP0844'],
		['meta' => 'Abai Begey and Berik - Aspanga (Official video)', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2aMpbJuFDNI'],
		['meta' => 'Inkar Abdirash - "Bright moon on a windless night"', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2RiL-95RZu8'],
		['meta' => 'Abdijappar Alkozha Collection 2019', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2T1nNfCGZxo'],
		['meta' => 'Sevinch Mo\'minova - Hayot (Konsert) | Севинч Муминова Хайот', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2VJdUCn0LTY'],
	],
	'channel' => [
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Bw3PwZIGL91PgEIOl9rG4Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'bXxDeRooSdj4oy6ncSPaBg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'c6i4tDpci2i5CJ1OgLlbJA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'c8XPLx-d2D4u5bpggzXfHQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'DPa8sA9N9piM2tTyNy5AGg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'DPnSqLmYqHadD6VkrRiarg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'E0-F3COrEs4JO-CxePqQdg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Ew_RG3hCpx4WIrWYFx963Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'eZydwrikhNCFN2UTar7hsA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'g7YNHS1ld_LBCupWa1I_AQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'GBxbj_RMKB22rhJnK9qReg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'hfvEI2V6kh1KlnjD_9SQHw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'hnQ9_PyEXfRQTcbU2cFhuQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'I0xlbO7RhAYtRohcc105RQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'i1upZDokdR7e1yC_dUg9hA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'JAF6d0FV9jeRQQ9HN6RbWQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'JhElX7IqOBQz6-3dkYShVw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'KJAFiS-wsF6W11TcbTaQBA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'kLqQDtC-bopErk6KRML5mg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'l61gYfkqRaH_S_JIQxSnZA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'LA_DiR1FfKNvjuUpBHmylQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'mDVoizxeZuCYSzVLLdHmGA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'myoEYCS02CYh_37c7HIMCw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Nye-wNBqNL5ZzHSJj3l8Bg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'OBmXp_2O09zqNR5qv2Qr-A'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'OmNoRQdKuszxn9TkFlk6rA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'qbNfBNv0A4vT0dLohqjbBg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'qmTZM-25uD0IXdD_K1Njjg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'QuQVcesmrsNGSpgLP8GBMQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'R_kWwq3R_14x95R6AJYI-Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'rKEIMHgsjev4giV_OKhdRg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'RKiInEnb1nWqHemAGDwGsQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'rpQ4p1Ql_hG8rKXIKM1MOQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'RyylBRddiZewwa7de2Bi6Q'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'S-kRm9CJWtxze3IfVoM0lQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'T3trmjOHDKO21aa-1Yivcg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'u9I-XjQebgjc00dibZ71Nw'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'UlHYnrVhTU5-FgowDLnbKg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'upwrZriiPNYXB2UR_FSc_w'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'VgAhHDsNIz44jjErLpvYXA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'vqMhkX3bcgbNosLTAJ-t1w'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'W1rf82JTgAk-0A9h28BTLQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'wnDGKPgpRsJUjuSGhATAmg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'wsUP-ropwm_HsckPJh65Hg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'WushebSpTZqRmYwVE9QxXg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Xb8kW7zaOtbjmaBU6udbmQ'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'XhOdeEtuMNihEU6OiyPeNg'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ynFmFoRYWJcCOjVdkK53dA'],
		['meta' => '', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'yv_mqSX7oUazpGLEAoX5zg'],
		['meta' => 'Agugai Tv', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '6D-YKTdwUdr05TTWeS9X1g'],
		['meta' => 'Akerke Togisova', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '_PQL4mfbfX_pblvTcO8nKg'],
		['meta' => 'eska muhamed', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2ILL_xyYYRPjkiECTQ_QUA'],
		['meta' => 'GAKKU TV', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '9xj5GKA0-Dr_filKO9YbnA'],
		['meta' => 'Julia Julia', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'ACh8qRSwUY1-HVyHxPTLsg'],
		['meta' => 'Kaz Music', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '9vDSJNvaWqORTs6ktGQVgQ'],
		['meta' => 'Nurlan Shulakov', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '6TZI5AYuQdWMXXfiKTAt7w'],
		['meta' => 'Panjsher Pro', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '4asVdurk3W_NMGdw40mjLA'],
		['meta' => 'Russian Music Collection 2020', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '2l9qE9hbg2fX4I9rYfSvXQ'],
		['meta' => 'Vip.Aşgabat', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '_Mvv-zVtidF_NAFySvQThA'],
		['meta' => 'Yevgeniy Grishayev', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '0IKcMMbi_K1a6B58PGQ91g'],
		['meta' => 'Нұрбол Сәрсенбайұлы / Nurbol Sarsenbayevich', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'BaKYRYWMaDjmBWA0kCb8PQ'],
		['meta' => 'тəрбиелі видеолар / educational videos', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '6iL0L4PTZCBTN0RiWsOfPw'],
		['meta' => 'ТОЙ ДУМАН', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => '-o7jbSVKsgX53b10fpxvtw'],
	],
	'user' => [
		['meta' => 'Alen Niyazbekov', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'pliund'],
		['meta' => 'Alihan Samedov', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'alihansamedov'],
		['meta' => 'Alma Studio Music', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Almastudiomusic'],
		['meta' => 'Avtoprobeg80', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Avtoprobeg80'],
		['meta' => 'Dauren Muhamed', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'MuhamedDJ'],
		['meta' => 'Erlan1982', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Erlan1982'],
		['meta' => 'Gakku TV', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'gakkutv'],
		['meta' => 'kazakhbeauty777', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'kazakhbeauty777'],
		['meta' => 'kaztubekz', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'kaztubekz'],
		['meta' => 'Leverage-kz', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'kemalus1'],
		['meta' => 'Made in KZ', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'krey1000'],
		['meta' => 'Morris Green', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'allstudio2012'],
		['meta' => 'NechtoMarGo', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'NechtoMarGo'],
		['meta' => 'NuraleM Ka', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Nuralem'],
		['meta' => 'Paul Friedrich', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Sawadila'],
		['meta' => 'RizaNovaUZ', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'RizaNovaUZ'],
		['meta' => 'Ruslan Jardem', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'RuslanJardem'],
		['meta' => 'Steppenblume', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Symbatik'],
		['meta' => 'The Voice Kids Russia', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'voicekids1tv'],
		['meta' => 'Алтай, Іле, Тарбағатай әндері мен әншілері', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Arman67Azatule'],
		['meta' => 'Казахтелеком', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'Kazakhtelecom'],
		['meta' => 'Мадияр Мукенов', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'opovis7'],
		['meta' => 'Нуржан Тажикенов', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'worldfilmnew'],
		['meta' => 'ART.IRBIS Production', 'artist' => '', 'artistQ' => '', 'title' => '', 'titleQ' => '', 'tag' => 'xusenru'],
	],
	'other' => [],
];

